API:
  HOST: 0.0.0.0:4518
  READ_TIMEOUT: 5s
  WRITE_TIMEOUT: 5s
  IDLE_TIMEOUT: 180s
  SHUTDOWN_TIMEOUT: 20s
  
DEBUG:
  HOST: 0.0.0.0:4519
  READ_TIMEOUT: 180s
  WRITE_TIMEOUT: 180s
  IDLE_TIMEOUT: 180s
  SHUTDOWN_TIMEOUT: 20s
